use sqlx_core::config::Config;
use std::hash::{BuildHasherDefault, DefaultHasher};
use std::io;
use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex};

use crate::query::cache::{MtimeCache, MtimeCacheBuilder};
use sqlx_core::HashMap;

pub struct Metadata {
    pub manifest_dir: PathBuf,
    pub config: Config,
    env: MtimeCache<Arc<MacrosEnv>>,
    workspace_root: Arc<Mutex<Option<PathBuf>>>,
}

pub struct MacrosEnv {
    pub database_url: Option<String>,
    pub offline_dir: Option<PathBuf>,
    pub offline: Option<bool>,
    /// Set by `cargo sqlx prepare --per-crate`; changes the layout of `offline_dir` so that
    /// each Cargo package gets its own subdirectory.
    ///
    /// Deliberately not read from `.env` files: this is an implementation detail of
    /// `sqlx-cli` and not something a project should configure for itself.
    pub offline_per_crate: bool,
}

/// Resolve the directory that query data generated by this invocation should be written to,
/// and that cached query data should be read from first.
///
/// Returns `None` if the current build isn't saving query data at all.
pub fn save_dir(env: &MacrosEnv) -> crate::Result<Option<PathBuf>> {
    let Some(offline_dir) = env.offline_dir.as_deref() else {
        return Ok(None);
    };

    if !env.offline_per_crate {
        return Ok(Some(offline_dir.to_path_buf()));
    }

    // `CARGO_PKG_NAME` is set by Cargo for the crate currently being compiled, which is the
    // crate that invoked the macro (the same way we use `CARGO_MANIFEST_DIR`).
    let package_name = crate::env("CARGO_PKG_NAME")?;

    Ok(Some(per_crate_save_dir(offline_dir, &package_name)))
}

/// The layout `cargo sqlx prepare --per-crate` expects inside `SQLX_OFFLINE_DIR`:
/// one subdirectory per Cargo package.
///
/// Package names are unique within a workspace and are restricted to characters that are
/// valid in a single path component, so the name can be used as the key directly.
fn per_crate_save_dir(offline_dir: &Path, package_name: &str) -> PathBuf {
    offline_dir.join(package_name)
}

impl Metadata {
    pub fn env(&self) -> crate::Result<Arc<MacrosEnv>> {
        let workspace_root = self.workspace_root();

        self.env.get_or_try_init(|builder| {
            load_env(&self.manifest_dir, &workspace_root, &self.config, builder)
        })
    }

    pub fn workspace_root(&self) -> PathBuf {
        let mut root = self.workspace_root.lock().unwrap();
        if root.is_none() {
            use serde::Deserialize;
            use std::process::Command;

            let cargo = crate::env("CARGO").unwrap();

            let output = Command::new(cargo)
                .args(["metadata", "--format-version=1", "--no-deps"])
                .current_dir(&self.manifest_dir)
                .env_remove("__CARGO_FIX_PLZ")
                .output()
                .expect("Could not fetch metadata");

            #[derive(Deserialize)]
            struct CargoMetadata {
                workspace_root: PathBuf,
            }

            let metadata: CargoMetadata =
                serde_json::from_slice(&output.stdout).expect("Invalid `cargo metadata` output");

            *root = Some(metadata.workspace_root);
        }
        root.clone().unwrap()
    }
}

pub fn try_for_crate() -> crate::Result<Arc<Metadata>> {
    /// The `MtimeCache` in this type covers the config itself,
    /// any changes to which will indirectly invalidate the loaded env vars as well.
    #[expect(clippy::type_complexity)]
    static METADATA: Mutex<
        HashMap<String, Arc<MtimeCache<Arc<Metadata>>>, BuildHasherDefault<DefaultHasher>>,
    > = Mutex::new(HashMap::with_hasher(BuildHasherDefault::new()));

    let manifest_dir = crate::env("CARGO_MANIFEST_DIR")?;

    let cache = METADATA
        .lock()
        .expect("BUG: we shouldn't panic while holding this lock")
        .entry_ref(&manifest_dir)
        .or_insert_with(|| Arc::new(MtimeCache::new()))
        .clone();

    cache.get_or_try_init(|builder| {
        let manifest_dir = PathBuf::from(manifest_dir);
        let config_path = manifest_dir.join("sqlx.toml");

        builder.add_path(config_path.clone());

        let config = Config::try_from_path_or_default(config_path)?;

        Ok(Arc::new(Metadata {
            manifest_dir,
            config,
            env: MtimeCache::new(),
            workspace_root: Default::default(),
        }))
    })
}

fn load_env(
    manifest_dir: &Path,
    workspace_root: &Path,
    config: &Config,
    builder: &mut MtimeCacheBuilder,
) -> crate::Result<Arc<MacrosEnv>> {
    #[derive(thiserror::Error, Debug)]
    #[error("error reading dotenv file {path:?}")]
    struct DotenvError {
        path: PathBuf,
        #[source]
        error: dotenvy::Error,
    }

    let mut from_dotenv = MacrosEnv {
        database_url: None,
        offline_dir: None,
        offline: None,
        offline_per_crate: false,
    };

    // https://github.com/launchbadge/sqlx/issues/4276
    let dirs = if manifest_dir.starts_with(workspace_root) {
        // Often just `[manifest_dir, workspace_dir]` but project structures can absolutely
        // be more complicated
        manifest_dir
            .ancestors()
            .take_while(|dir| dir.starts_with(workspace_root))
            .collect::<Vec<_>>()
    } else {
        // Thinking of edge cases, there's the possibility that the package directory
        // isn't actually a child of the workspace directory. There isn't really any other sane
        // thing to do here; we shouldn't traverse into unrelated paths.
        [manifest_dir, workspace_root].to_vec()
    };

    for dir in dirs {
        let path = dir.join(".env");

        let dotenv = match dotenvy::from_path_iter(&path) {
            Ok(iter) => {
                builder.add_path(path.clone());
                iter
            }
            Err(dotenvy::Error::Io(e)) if e.kind() == io::ErrorKind::NotFound => {
                builder.add_path(dir.to_path_buf());
                continue;
            }
            Err(e) => {
                builder.add_path(path.clone());
                return Err(DotenvError { path, error: e }.into());
            }
        };

        for res in dotenv {
            let (name, val) = res.map_err(|e| DotenvError {
                path: path.clone(),
                error: e,
            })?;

            match &*name {
                "SQLX_OFFLINE_DIR" => from_dotenv.offline_dir = Some(val.into()),
                "SQLX_OFFLINE" => from_dotenv.offline = Some(is_truthy_bool(&val)),
                _ if name == config.common.database_url_var() => {
                    from_dotenv.database_url = Some(val)
                }
                _ => continue,
            }
        }
    }

    Ok(Arc::new(MacrosEnv {
        // Make set variables take precedent
        database_url: crate::env_opt(config.common.database_url_var())?
            .or(from_dotenv.database_url),
        offline_dir: crate::env_opt("SQLX_OFFLINE_DIR")?
            .map(PathBuf::from)
            .or(from_dotenv.offline_dir),
        offline: crate::env_opt("SQLX_OFFLINE")?
            .map(|val| is_truthy_bool(&val))
            .or(from_dotenv.offline),
        offline_per_crate: crate::env_opt("SQLX_OFFLINE_PER_CRATE")?
            .is_some_and(|val| is_truthy_bool(&val)),
    }))
}

/// Returns `true` if `val` is `"true"` (case-insensitive) or `"1"`.
fn is_truthy_bool(val: &str) -> bool {
    val.eq_ignore_ascii_case("true") || val == "1"
}

#[cfg(test)]
mod tests {
    use super::*;

    fn env(offline_dir: Option<&str>, offline_per_crate: bool) -> MacrosEnv {
        MacrosEnv {
            database_url: None,
            offline_dir: offline_dir.map(PathBuf::from),
            offline: None,
            offline_per_crate,
        }
    }

    #[test]
    fn save_dir_is_none_without_offline_dir() {
        assert_eq!(save_dir(&env(None, false)).unwrap(), None);
        // Nothing to be per-crate about if we're not saving anything.
        assert_eq!(save_dir(&env(None, true)).unwrap(), None);
    }

    #[test]
    fn save_dir_is_offline_dir_by_default() {
        assert_eq!(
            save_dir(&env(Some("/tmp/sqlx-prepare"), false)).unwrap(),
            Some(PathBuf::from("/tmp/sqlx-prepare"))
        );
    }

    // `crate::env()` reads `CARGO_PKG_NAME` through `proc_macro::tracked`
    // under these cfgs, which panics outside of a proc macro invocation.
    #[cfg(not(any(sqlx_macros_unstable, procmacro2_semver_exempt)))]
    #[test]
    fn save_dir_is_per_package_when_enabled() {
        assert_eq!(
            save_dir(&env(Some("/tmp/sqlx-prepare"), true)).unwrap(),
            Some(PathBuf::from("/tmp/sqlx-prepare").join(env!("CARGO_PKG_NAME")))
        );
    }

    #[test]
    fn per_crate_save_dir_is_a_subdirectory_per_package() {
        assert_eq!(
            per_crate_save_dir(Path::new("/tmp/sqlx-prepare"), "my-api"),
            PathBuf::from("/tmp/sqlx-prepare/my-api")
        );
    }
}
